### ISSUE TITLE
Неработоспособное приложение начиная с 39c5932d999b7dd51c46324fc1e733c2c3cc2ac4

### ISSUE THREAD

**Issue by ValeriyKr** [zhmylove/itmmorgue#18]
Код, добавленный в 39c5932d999b7dd51c46324fc1e733c2c3cc2ac4, под линуксом требует тщательной отладки, ибо при запущенном сервере из главного меню пункт "2" не работает совсем, а "1" приводит к падению приложения по SIGCHLD.

**Comment by ValeriyKr** [comment]
В частности, попыток соединиться тут и нет:
```
read(0, "2", 1)                         = 1
write(1, "\33[39;49m\33[37m\33[40m\33[H\33[2J\33[24;42"..., 235) = 235
read(0, "2", 1)                         = 1
write(1, "\33[39;49m\33[37m\33[40m\33[H\33[2J\33[24;42"..., 235) = 235
read(0, "2", 1)                         = 1
write(1, "\33[39;49m\33[37m\33[40m\33[H\33[2J\33[24;42"..., 235) = 235
read(0, "2", 1)                         = 1
write(1, "\33[39;49m\33[37m\33[40m\33[H\33[2J\33[24;42"..., 235) = 235
read(0, "2", 1)                         = 1
write(1, "\33[39;49m\33[37m\33[40m\33[H\33[2J\33[24;42"..., 235) = 235
```

**Comment by zhmylove** [comment]
Плохо дебажишь и плохо знаешь код.
Пункт 2 работает как нужно: там меню m_null.

>В частности, попыток соединиться тут и нет:
Судя по выводу, кто-то не умеет в strace.

SIGCHLD на линупсе -- известная тема. Скоро поправлю.

**Comment by zhmylove** [comment]
Любопытно, что SIGCHLD только при попытке запустить сервер в headless mode.
Нечего пытаться запускать два сервера одновременно :)
Здесь вам не freebsd, где всё работает как часы.

**Comment by ValeriyKr** [comment]
Значит, логично словив SIGCHLD сказать пользователю, что сервер уже запущен.

**Comment by zhmylove** [comment]
Пойманный SIGCHLD говорит только о том, что подпроцесс сервера завершился. Он мог завершиться по любой причине.
