### ISSUE TITLE
Broken scrolling in small sysmsg window

### ISSUE THREAD

**Issue by ValeriyKr** [zhmylove/itmmorgue#39]
If you start the game with embedded server, open chat and send a few message, you will see that small sysmsg window shows not the last notification. Sometimes, it works correctly for a few messages, but in common case it doesn't.

Tested on GNU/Linux.

**Comment by ValeriyKr** [comment]
To be more concrete, проблема заключается в том, что мы видели раньше, а именно: scrolling works with delay and we have to send a few messages to see some of previous.

**Comment by zhmylove** [comment]
Проблема копипасты, связанная со скроллоффом?
Или у нас разный код скроллофа?

**Comment by ValeriyKr** [comment]
А вот хз. Возможно, мы пофиксили что-то в оригинальном коде, но это не было портировано в копипащенный.

**Comment by zhmylove** [comment]
draw_sysmsg() нужно реализовать из починенного draw_chat (файл chat.c)
