### ISSUE TITLE
Доделать gen.pm для генерации густо расположенных объектов

### ISSUE THREAD

**Issue by ValeriyKr** [zhmylove/itmmorgue#45]
Нужна функциональность, описанная выше, для генерации, например, городов. overlay_anywhere здесь подходит плохо.

**Comment by zhmylove** [comment]
Это почему не подходит?
См. gen_city.pl
Там создаётся уровень, который заполняется ',' -- на него нужно располагать здания (сейчас это уже работает).

**Comment by ValeriyKr** [comment]
Да, я был не прав. Мне не хватало ширины экрана сделать всё нормально и увидеть. Не код же читать, право.
